### ISSUE TITLE
sql_like_escape() not used in data_field_tag::generate_sql()

### ISSUE THREAD

**Issue by mudrd8mz** [andrewhancox/datafield_tag#4]
See https://docs.moodle.org/dev/Data_manipulation_API#SQL_compatibility_functions and how `$DB->sql_like_escape()` is used elsewhere in the Moodle code.

**Comment by mudrd8mz** [comment]
To simply check, searching for tag text "%" probably returns all records.

**Comment by andrewhancox** [comment]
Done
